/*
 * This source file was generated by the Gradle 'init' task
 */
package magentoapps;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;

import io.github.bonigarcia.wdm.WebDriverManager;


class DashboardTest {

    @Test
    public void testDashboardPage() {
        WebDriver driver = WebDriverManager.chromedriver().create();

        DashboardPage dashboardPage = new DashboardPage(driver);

        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(java.time.Duration.ofSeconds(10));
        driver.get("https://magento.softwaretestingboard.com/");

        dashboardPage.clickOnNavibar();
        dashboardPage.clickOnAccountTab();
        dashboardPage.clickOnCreateAccountLink();
        dashboardPage.getRegisterValidationText();
    }
}
