name: Pipeline CI Automation Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  runs-automations-test:

    runs-on: ubuntu-latest

    steps:
    #download repo
    - uses: actions/checkout@v4

    #setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    #install chrome browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0

    # setup gradle
    - name: Setup Gradle
      run: chmod +x gradlew

    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew test --tests "config.Runner"

    # Archive Test Result
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Report
        path: app/build/reports/tests/test
      
    # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: reports
